### ISSUE TITLE
Error on order's detail page

### ISSUE THREAD

**Issue by Fe1ix97** [wpswings/woo-refund-and-exchange-lite#102]
our customers cannot open a return request

`Fatal error: Uncaught Error: Call to a member function get_name() on bool in /home/customer/www/***/public_html/wp-content/plugins/woo-refund-and-exchange-lite/public/class-woo-refund-and-exchange-lite-public.php:257 Stack trace: #0 /home/customer/www/***/public_html/wp-includes/class-wp-hook.php(308): Woo_Refund_And_Exchange_Lite_Public->wps_rma_return_button_and_details(Object(Automattic\WooCommerce\Admin\Overrides\Order)) #1 /home/customer/www/***/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #2 /home/customer/www/***public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /home/customer/www/***/public_html/wp-content/plugins/woocommerce/templates/order/order-details.php(100): do_action('woocommerce_ord...', Object(Automattic\WooCommerce\Admin\Overrides\Order)) #4 /home/customer/www/***/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/customer/...') #5 /home/customer/www/ in /home/customer/www/***/public_html/wp-content/plugins/woo-refund-and-exchange-lite/public/class-woo-refund-and-exchange-lite-public.php on line 257`

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Shivamddeveloper** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
