### ISSUE TITLE
Add video link on description links

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#103]
Woocoomerce: 7.6.0
WordPress: 6.2.0
Version: 5.0.9
Description:
Add video link on description links
![image](https://user-images.githubusercontent.com/85384857/233641410-c50298e1-640d-4d74-a8af-b4b5baa2a3c8.png)

![image](https://user-images.githubusercontent.com/85384857/233630480-21c944a8-5528-4b23-a538-a9e4ea96420c.png)

**Comment by Shivamddeveloper** [comment]
link added

**Comment by pranjali-wps** [comment]
verified

**Comment by Sukirti-CEDCOSS** [comment]
verified
