### ISSUE TITLE
Save settings button issue on integration setting

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#105]
WP Ver- 6.2.2
WC Ver- 7.7.1
plugin- 4.2.0
Description- Save settings button is not proper on integration setting(also Validate account button)

[scrnli_30_05_2023_12-38-51.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/125f2e19-483c-4ba2-adaf-61e529854bd1)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue fixed
