### ISSUE TITLE
Cancel setting issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#107]
WP Ver.- 6.2.2
WC Ver.- 7.7.2
Plugin Ver.- 4.2.0
Description- When I have Click on "Click Here" to configure the Email settings, it is conflicted. 

Steps to be followed- 
1. Go to WPSwings --> Return Refund and Exchange for WooCommerce.
2. Cancel settings--> Scroll down and click on "Click Here".

[scrnli_02_06_2023_13-18-13.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/db78e70d-46da-4a7a-95f8-4cfd1900cfe7)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue fixed
