### ISSUE TITLE
Global shipping setting issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#108]
WP Ver.- 6.2.2
WC Ver.- 7.7.2
Plugin Ver.- 4.2.0
Description- When I have Click on "Save setting" button on Global shipping setting page it is displayed a Pro Pop-up which is not valid.
Steps to be followed
Go to WPSwings --> Return Refund and Exchange for WooCommerce.
Global shipping settings--> Scroll down and click on "Save Setting".
[scrnli_02_06_2023_13-24-02.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/f6b18151-78f0-43b2-a40c-10f245411f30)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue resolved
