### ISSUE TITLE
In Integration setting ,Click here button is not working properly.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#110]
WP Ver.- 6.2.2
WC Ver.- 7.7.2
Plugin Ver.- 4.2.0
Description- When I have Click on "Click Here" to configure the Email settings, it is conflicted.

Steps to be followed-
Go to WPSwings --> Return Refund and Exchange for WooCommerce.
Integration settings--> Scroll down and click on "Click Here".
[scrnli_02_06_2023_14-25-25.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/574448e6-6925-4c0f-9bf7-751bf6b2fd1d)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
Issue fixed
