### ISSUE TITLE
In ShipRocket Integration tab , Save setting button is not working properly 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#111]
WP Ver.- 6.2.2
WC Ver.- 7.7.2
Plugin Ver.- 4.2.0
Description- In ShipRocket Integration tab, When I have click on save setting button then Enter Your API User Email Description is displayed .
Step to be followed-
1.Go to WPSwings --> Return Refund and Exchange for WooCommerce.
2.Integration settings--> ShipRocket Integration-->Click on Save setting.

[scrnli_02_06_2023_15-21-42.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/bbf545aa-6a04-42be-a0af-bf2b5ac1066b)

**Comment by mohammaddanish-cedcoss** [comment]
fixed
