### ISSUE TITLE
Error on Page Refund Request Form

### ISSUE THREAD

**Issue by anuj-yadav-11** [wpswings/woo-refund-and-exchange-lite#112]
Error:
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

I am only getting this error on the Refund Request Form Page and all other pages of the website are working fine.
![Capture](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/107611735/cc679044-55e1-4feb-a952-979be04efd19)

**Comment by Shivamddeveloper** [comment]
already solved in lastest version
