### ISSUE TITLE
Unnecessary Boxes are displayed on thank you page

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#113]
WP Beta version- 6.3
WC Beta version- 8.0.0
Plugin version- 4.2.1

Description - Unnecessary Boxes are displayed on thank you page on different types of themes.
**Storefront**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/c21fd9dc-e48a-45df-b74a-da8d009f9880)

**Avada**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/e4139f9e-1c27-44be-a757-e7a12c81c69a)

**BeTheme**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/f581fa90-3646-4c03-8f72-fabcd02600d9)

**Divi**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/5a7cbd76-b449-4db7-8788-22f082327f75)

**Flatsome**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/926f1102-f30c-43ab-912d-9b9c10932aa2)

**OceanWP**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/f1a751a0-6916-405a-aaf0-8f0923b22a4f)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
