### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#114]
WP beta version- 6.3
WC beta version- 8.0.0
Plugin - 4.2.1
Description- Widgets are scattered on the view order message page.
**Storefront**
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/6550bf60-e66f-4501-a103-9003e2c44660)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
1)When I have enabled the attachment for order messages then the "Send" button is attached with the message history headline.
2)Please provide the "Refresh button" in a proper way. 
![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/67f418dc-ae76-4235-9b08-a4b553e32b73)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
