### ISSUE TITLE
 There should be validation for incorrect time intervals. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#122]
WP Version - 6.3.2
WC Version - 8.2.1
plugin- 4.3.2
Description- There should be validation for incorrect time intervals and also add a tooltip for Feature explanation(working for a day and other)

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/c23b1e8c-373c-4b7d-852b-f2c3dd95c65a)

**Comment by mohammaddanish-cedcoss** [comment]
added

**Comment by pranjali-wps** [comment]
issue fixed
