### ISSUE TITLE
When I activate plugin then got fatal error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#123]
WP Version - 6.3.2
WC Version - 8.2.1
plugin- 4.3.2
Description- When I activate plugin then got fatal error.

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/7efe3140-5a95-4d0b-9a48-72d9ab67a4c3)

**Comment by mohammaddanish-cedcoss** [comment]
resolved

**Comment by pranjali-wps** [comment]
issue fixed
