### ISSUE TITLE
Deprecated is displayed

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#126]
WP Version - 6.4.2
WC Version - 8.5.0
plugin- 4.3.5
Description- Deprecated is displayed

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/343b64ad-a632-44f3-93b4-82600e16a997)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by pranjali-wps** [comment]
issue fixed
