### ISSUE TITLE
 The attachment is not uploaded in the backend View order message.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#127]
WP Version - 6.4.2
WC Version - 8.5.0
plugin- 4.3.5
Description  - The attachment is not uploaded in the backend View order message.
Issue - If I have enabled the setting RMA setting-->Order Message-->Enable Attachment - Then from the backend Attachment is uploaded. 

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/758bda47-aed1-47c6-a63a-3ddfe3256637)

[scrnli_12_01_2024_13-58-41.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/62d85c83-af7b-467a-92d1-a2d24707b91d)

**Comment by Shivamddeveloper** [comment]
issue fixed now attach file functionality only work when enable attachement setting is enable for both frontend and backend
