### ISSUE TITLE
Notice is displayed on order details page on backend and frontend  

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#128]
WP Version - 6.4.3
WC Version - 8.6.0
Plugin Version - 4.3.6
Description -
**1)** Notice is displayed on order details page on the backend and frontend.

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/5fa7ad9f-4444-4059-acaf-98755c9716b4)

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/4c18e001-becd-439b-84fe-01838f8b0004)

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/5aa4e65f-8701-4b49-b07a-c9cf14178362)

**Comment by Shivamddeveloper** [comment]
now all visible notice are solved

**Comment by pranjali-wps** [comment]
issue fixed
