### ISSUE TITLE
PHPCS ISSUE

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#129]
WP Version - 6.4.3
WC Version - 8.6.0
Plugin Version - 4.3.6
Description - PHPCS ISSUE

[PHPcs_ORG.docx](https://github.com/wpswings/woo-refund-and-exchange-lite/files/14385274/PHPcs_ORG.docx)

**Comment by Shivamddeveloper** [comment]
phpcs issue are fixed except includes folder common file related to nonce verification, so for this we need to ignore because we have already verify the nonce verification via calling same function

**Comment by pranjali-wps** [comment]
verified
