### ISSUE TITLE
If I have a refund for a Booking product then it displays a notice "Selected product must have the quantity" 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#130]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 4.3.8 
Description  - If I have a refund for a Booking product then it displays a notice "Selected product must have the quantity" 

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/6f8c1747-5a10-47a5-9700-3caab7a318e2)

[scrnli_26_04_2024_11-45-29.webm](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/e6d2ac97-817c-42d9-8975-b78ffe514c14)

**Comment by mohammaddanish-cedcoss** [comment]
issue has been fixed

**Comment by pranjali-wps** [comment]
issue fixed
