### ISSUE TITLE
 If I have deleted the WooCommerce from the Backend(Woocommerce file folder) then displayed a fatal error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#134]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - ORG
Description - If I have deleted the WooCommerce from the Backend(Woocommerce file folder) then displayed a fatal error.

![image](https://github.com/wpswings/woo-refund-and-exchange-lite/assets/129398279/28fc76e8-aaf4-4fc1-9e06-a74ed087ad8f)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by pranjali-wps** [comment]
issue fixed
