### ISSUE TITLE
 The unwanted message was displayed on the order details page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#137]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 4.4.3 
Description - The unwanted message was displayed on the order details page.

![image](https://github.com/user-attachments/assets/f515104e-29e0-4024-a86a-93175fdcfe54)

![image](https://github.com/user-attachments/assets/b95389f4-a646-4cce-81ba-86e64ff0c8c8)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
