### ISSUE TITLE
Fatal error displayed on variable product

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-refund-and-exchange-lite#138]
WP Version - 6.6.2
WC Version - 9.3.3
Plugin Version - 4.4.3
Description - Fatal error displayed on a variable product if I have enabled the "Enable Exchange Request With Same Product Or Its Variations" field

![image](https://github.com/user-attachments/assets/e4c69bf0-4196-4274-8100-01613b3d6211)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue  fixed
