### ISSUE TITLE
While accepting the return request the loader appeared for the much longer time

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#42]
WordPress: 5.9.1
WooCommerce: 6.3.0
Description:
While accepting the return request the loader appeared for the much longer time
![image](https://user-images.githubusercontent.com/85384857/157802818-e03947c6-bc5e-48ec-9406-f64b30717cf0.png)

**Comment by mohammaddanish-cedcoss** [comment]
working fine

**Comment by Sukirti-CEDCOSS** [comment]
verified
