### ISSUE TITLE
Error notices 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#43]
WordPress: 5.9.1
WooCommerce: 6.3.0
Description:
Showing notices on homepage 
![image](https://user-images.githubusercontent.com/85384857/158573426-e285bb3f-f2d3-4654-ae7b-a926d746e6fe.png)

Showing PHP Query 
![image](https://user-images.githubusercontent.com/85384857/158574634-f3ac254f-8f2b-464c-94d8-f8249666dcb8.png)

**Comment by mohammaddanish-cedcoss** [comment]
Fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
