### ISSUE TITLE
There is a continuous loader while check out

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#44]
WordPress: 5.9.1
WooCommerce: 6.3.0
Description:
There is a continuous loader while check out 
![image](https://user-images.githubusercontent.com/85384857/158575392-c906e603-a227-4851-85bd-abf50b367fa8.png)

**Comment by mohammaddanish-cedcoss** [comment]
Working fine. Please try again on the fresh site.

**Comment by Sukirti-CEDCOSS** [comment]
on the 2nd site, this is Still happening 
![image](https://user-images.githubusercontent.com/85384857/159239857-44f1a6a1-8620-44ac-80fa-657010359e7e.png)

**Comment by Sukirti-CEDCOSS** [comment]
it is working but after we reduce the version of the plugin then after the update tries to place an order this issue occurs.

**Comment by mohammaddanish-cedcoss** [comment]
there is some problem in the PayPal payment setup that's why it is showing continuously loader. I tried by deactivating the RMA plugins.

**Comment by Sukirti-CEDCOSS** [comment]
verified
