### ISSUE TITLE
The notice "start migration" should not display after the import was successful .

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#45]
WordPress: 5.9.1
WooCommerce: 6.3.0
Description:
The notice should not display after the import was successful .
![image](https://user-images.githubusercontent.com/85384857/159240252-1b8751a0-d28c-46ad-89de-dc8f065f7e6b.png)

**Comment by mohammaddanish-cedcoss** [comment]
done

**Comment by Sukirti-CEDCOSS** [comment]
verified
