### ISSUE TITLE
The Go Premium notice is showing where the pro plugin of the latest boilerplate is active 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#52]
WC: 6.4.1
WP: 5.9.3
Description:
The Go Premium notice is showing where the pro plugin of the latest boilerplate is active 
![image](https://user-images.githubusercontent.com/85384857/164402258-2e0440b7-955c-4d13-9d0d-99cd29a0b4f7.png)

**Comment by mohammaddanish-cedcoss** [comment]
it is working fine.

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
