### ISSUE TITLE
Please remove the notice

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#53]
WC: 6.4.1
WP: 5.9.3
Description:
You can remove this notice :
![image](https://user-images.githubusercontent.com/85384857/164402729-a66c44bb-ac47-4299-a52c-82121f81a81a.png)

**Comment by mohammaddanish-cedcoss** [comment]
remove notices

**Comment by Sukirti-CEDCOSS** [comment]
verified
