### ISSUE TITLE
The plugin name should be properly mentioned not the text-domain in the plugin name area

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#54]
WC 6.4.1
WP: 5.9 3 
Description:
In the Onboarding and Deactivation form
The plugin name should be properly mentioned not the textdomain in the plugin name area
![image](https://user-images.githubusercontent.com/85384857/164714788-113f86c3-db13-4a5b-9420-c16677f7273f.png)

![image](https://user-images.githubusercontent.com/85384857/164714724-f83e1e17-20d8-4c46-84a0-fd9dc6257612.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
