### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#57]
There is an issue when I replaced the ORG new plugin with olg ORG plugin 
![image](https://user-images.githubusercontent.com/85384857/166934038-8cf2c77c-f6f8-4af7-9d42-d11cbcb53a92.png)

**Comment by mohammaddanish-cedcoss** [comment]
Fix

**Comment by Sukirti-CEDCOSS** [comment]
verified
