### ISSUE TITLE
On the message page, the attachment is also allowing pdf and doc files to send in messages but the image is not visible to the receiver side.

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#59]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description: 
On the message page, the attachment is also allowing pdf and doc files to send in messages but the image is not visible to the receiver side.
![image](https://user-images.githubusercontent.com/85384857/171610502-3c63e04f-e169-4c5f-ba79-e8637a7afa05.png)
![image](https://user-images.githubusercontent.com/85384857/171610621-b4e8e20c-e35d-481d-a1bf-d83419152f95.png)

**Comment by mohammaddanish-cedcoss** [comment]
Add some validation, Now only jpg/jpeg/png image format will be supported and it will be sent

**Comment by Sukirti-CEDCOSS** [comment]
Add the validation in refund and exchange form also
![image](https://user-images.githubusercontent.com/85384857/171989379-7f7b24a1-e4fd-4e8e-9d90-43939e5aef4d.png)

**Comment by Sukirti-CEDCOSS** [comment]
Can't we put the validation so that the message will not be sent with pdf file or the pdf file will not be able to upload int massage or in refund exchange form

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
