### ISSUE TITLE
There still the MWB logo in the image 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#60]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
There still the MWB logo in the image 
![image](https://user-images.githubusercontent.com/85384857/171617148-870f736c-24ab-48fc-a8ac-071d0b889eda.png)

**Comment by mohammaddanish-cedcoss** [comment]
Image updated

**Comment by Sukirti-CEDCOSS** [comment]
The image is still a little bit blurry, it's not in HD Quality. Loot at the WP logo you'll understand
![image](https://user-images.githubusercontent.com/85384857/171989063-b46ee890-9f70-4110-a99a-f4e5f9940636.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by mohammaddanish-cedcoss** [comment]
updated image with high quality

**Comment by Sukirti-CEDCOSS** [comment]
verified
