### ISSUE TITLE
If we are installing the woocomerce plugin with the site plugin the WP swing two menus option is showing

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#61]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
If we are installing the woocomerce plugin with the site plugin the WP swing two menus option is showing
![image](https://user-images.githubusercontent.com/85384857/171623890-d5184469-40c0-48ae-b3ae-05e1804a6e84.png)

**Comment by mohammaddanish-cedcoss** [comment]
This issue is coming from Partial COD plugin. There is a need for changes in the code of Partial cod plugin, They have used mwb prefix that's why it is showing another menu of that plugin. Please ask Partial Cod's developer to fix this issue.

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
