### ISSUE TITLE
The home option is not visible in the SP Swings menu 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#62]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
The home option is not visible in the SP Swings menu 
![image](https://user-images.githubusercontent.com/85384857/171624446-c45a3bab-6388-41fc-a028-39362b131278.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
