### ISSUE TITLE
One option should be chosen as default in the payment mode 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#63]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
One option should be chosen as default in the payment mode 
![image](https://user-images.githubusercontent.com/85384857/171641440-ed386f7c-8ba8-46ea-8474-ceae7b192e1b.png)

**Comment by mohammaddanish-cedcoss** [comment]
this issue is coming from Partial Cod plugin, Please talk to the plugin's developer for this.

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
