### ISSUE TITLE
Mail data is not proper

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#64]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
Mail data is not proper
![image](https://user-images.githubusercontent.com/85384857/171645953-526c4f74-770f-4bb3-b240-7e90f636e534.png)

**Comment by mohammaddanish-cedcoss** [comment]
You are using wrong shortcode, please use these available shortcode for RMA org
![screenshot-localhost_10033-2022 06 03-15_28_38](https://user-images.githubusercontent.com/76724269/171833287-71bc7e6b-f2b1-435e-8d41-a54dc8159f4b.png)

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
