### ISSUE TITLE
If the image upload is compulsory then put an asterisk mark beside heading

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#68]
WooComerce : 6.7.0
Word Press: 6.0.1
Description : 
If the image upload is compulsory then put an asterisk mark beside the heading
![image](https://user-images.githubusercontent.com/85384857/179342338-df298366-15b6-4654-9809-e51d4f92a6ee.png)

![image](https://user-images.githubusercontent.com/85384857/179342318-aa004845-968d-4e53-9518-2b279694e14c.png)

**Comment by mohammaddanish-cedcoss** [comment]
done

**Comment by Sukirti-CEDCOSS** [comment]
verified
