### ISSUE TITLE
the price of the product when tax is excluded is showing lesser than the actual amount

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#69]
WooComerce : 6.7.0
Word Press: 6.0.1
Description :
the price of the product when tax is excluded is showing lesser than the actual amount
![image](https://user-images.githubusercontent.com/85384857/179343822-7f3da15e-0e76-4bc2-b69d-9f9fdc2048b7.png)
![image](https://user-images.githubusercontent.com/85384857/179344753-2c914ea7-6c3f-4576-ace0-dcae0220f4b8.png)

**Comment by mohammaddanish-cedcoss** [comment]
it is showing the right price because you have set exclude tax policy that's why it is showing the price after subtracting the tax from the actual price

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
