### ISSUE TITLE
Onboarding form is not working

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#70]
WooComerce : 6.7.0
Word Press: 6.0.1
Description :
The onboarding form is not working

**Comment by mohammaddanish-cedcoss** [comment]
working fine, I am getting the onboarding form data

![screenshot-app-eu1 hubspot com-2022 07 18-13_03_28](https://user-images.githubusercontent.com/76724269/179464521-96727e4d-d387-4bcd-bba0-fb00c6b54460.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
