### ISSUE TITLE
Warning in policies page

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#74]
Warning in policies page :
![image](https://user-images.githubusercontent.com/85384857/197121189-b8a5689d-df35-4a1e-8285-ba1c998fc2e6.png)
![image](https://user-images.githubusercontent.com/85384857/197121271-75bc8bdf-8e98-41d9-b643-0c765c1bdffb.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
