### ISSUE TITLE
The image uploaded on the message form should be able to open on the admin side on the order page and customer page.

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#81]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description: The image uploaded on the message form should be able to open on the admin side on the order page and customer page.
![image](https://user-images.githubusercontent.com/85384857/202990905-74c27822-bf2b-496c-834d-c2f23bf6652a.png)

**Comment by Shivamddeveloper** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
