### ISSUE TITLE
design issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#82]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description:
Design Issue
![image](https://user-images.githubusercontent.com/85384857/202991505-ce6391f6-251c-42b3-a516-7740e2f8f2f3.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
