### ISSUE TITLE
Design Issue  with themes

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#83]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description:
Design Issue 
**OceanWP**
![image](https://user-images.githubusercontent.com/85384857/202995878-53714de7-19b1-44da-85bc-f7690555c0f7.png)
**Betheme**
![image](https://user-images.githubusercontent.com/85384857/202996255-c4d2c3de-4b51-4aea-a6ea-c72a3f3999c2.png)
**FLATESOME**
![image](https://user-images.githubusercontent.com/85384857/202997748-d5855d78-f642-480e-8c7a-a8037d208994.png)

**Comment by Shivamddeveloper** [comment]
checked and working properly

**Comment by Sukirti-CEDCOSS** [comment]
veridied
