### ISSUE TITLE
The update Refund request button is not working

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#88]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description:
The update Refund request button is not working, it should  navigate to the refund form to edit the request
![image](https://user-images.githubusercontent.com/85384857/203003053-3305e850-d2ae-4fdf-858f-dacb9fa6f265.png)
............................................................................................................
![image](https://user-images.githubusercontent.com/85384857/203003195-bf79f9fc-32de-4f32-ab72-641df57f590b.png)

**Comment by mohammaddanish-cedcoss** [comment]
make sure you have set the RMA policies so that They can show the refund form once the order status is refund request already

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
