### ISSUE TITLE
The image uploaded from the Customers side on the refund form is not visible on the order page

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#89]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description:
The image uploaded from the Customers side on the refund form is not visible on the order page
![image](https://user-images.githubusercontent.com/85384857/203004956-30f57e28-4fca-4bc5-87ef-c0f4fa717ac2.png)

**Comment by mohammaddanish-cedcoss** [comment]
this is working fine, Make the plugin must have write permission in the directory, So it can move the images

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
