### ISSUE TITLE
The heading for Bank Details: and Refund Reason: should be add in refund form

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#90]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description:
The heading for Bank Details: and Refund Reason: should be add in refund form, it would look more proper
![image](https://user-images.githubusercontent.com/85384857/203005293-e690606e-627d-4467-9e74-4385921da45d.png)

**Comment by mohammaddanish-cedcoss** [comment]
Added the heading for the bank account field
And for the refund reason subject has already heading of `subject of refund request`

**Comment by Sukirti-CEDCOSS** [comment]
verified
