### ISSUE TITLE
After exceeding the number of allowed Attachment files the "Add More" button should disappear

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#91]
WC: 7.1.0
WP: 6.1.0
Version: 4.0.8
Description:
After exceeding the number of allowed Attachment files the "Add More" button should disappear, it may lead to confusing the user
![image](https://user-images.githubusercontent.com/85384857/203014124-528af8a3-0fc7-4734-a462-01268193ed05.png)
![image](https://user-images.githubusercontent.com/85384857/203014171-b3e0fbe6-3591-48aa-a343-b193345fcce6.png)

**Comment by Shivamddeveloper** [comment]
this point will cover in next update of plugin

**Comment by Sukirti-CEDCOSS** [comment]
verified
