### ISSUE TITLE
When we are refunding the amount purchased using Gift Card, "Invalid amount " Warning appears 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#99]
Woo Commerce Version - 7.2.2
WordPress Version - 6.1.1
Plugin Version - 2.4.9
Description -
When we are refunding the amount purchased using Gift Card, an "Invalid amount " Warning appears 
![image](https://user-images.githubusercontent.com/85384857/211820577-3d7fda38-d777-405f-b3d2-4f8ba0f94c96.png)

**Comment by mohammaddanish-cedcoss** [comment]
please use the wallet method for Gc refund compatibility

**Comment by Sukirti-CEDCOSS** [comment]
verified
